### PR TITLE
Visual spec files

### PR DESCRIPTION
**Pull request by seejamescode**
**Changed**

- Sketch files are now hosted in `./visual-specs`
- Edit the particular chart file and then we will update `IBM-Design-Charts.sketch` during releases.

### CODE REVIEW

**Comment by joshblack** [comment]
Can we have a package like: `packages/charts-design` instead? Just for organization sake

**Comment by seejamescode** [comment]
Does this work, @joshblack?

**Comment by joshblack** [comment]
Should be fine, could copy Bluemix's design-kit structure: https://github.ibm.com/bluemix/design-kit

@winslet do we need to include any font files here or in a box to accompany the sketch files?

**Comment by seejamescode** [comment]
Agreed about copying Carbon Design Kit!

**Review by matthewgallo — APPROVED** [review]

**Pull request merged**
